### ISSUE TITLE
SPOTIFY IS BROKEN

### ISSUE THREAD

**Issue by kellub** [anickle060193/easy_control#105] opened 2017-03-07 13:30 UTC
ADAM! SPOOOTERFLEA UPDATED ITS WEB CLIENT AND NOW NOTHING WORKDS. I BET THAT YOU COULD MAKE EVERYTHING BETTER THOUGH THIS TIME. (MAYBE VOLUME CONTROL SO JACOB WILL SHUT UP ABOUT IT?)

**Comment by anickle060193** [comment] 2017-03-08 15:01
Duplicate of #106

**Closed as completed by anickle060193** 2017-03-08 15:01 UTC
Labels: bug, Spotify
