### ISSUE TITLE
Playback speed controls being weird

### ISSUE THREAD

**Issue by kellub** [anickle060193/easy_control#118] opened 2017-06-03 14:19 UTC
I have 's' for faster and 'S' for much faster. 'S' doesn't seem to do anything, and 's' executes the much faster operation. This has only occurred since the most recent update.

**Comment by anickle060193** [comment] 2017-06-03 19:14
This is most likely caused by how keyboard shortcut handling was changed by 9d3b00d9489bd9b7c9e33d7e3366de63f924a041. You may need to re-set your keyboard shortcuts for them to work with the new handling.

**Comment by allanlaal** [comment] 2017-09-08 08:12
@anickle060193  I have the same issue as @kellub - the increase playback speed shortcuts only work intermittedly. Updating them had no affect.

the "much faster/slower" seems to have stopped working too

**Comment by anickle060193** [comment] 2019-03-24 06:34
Closing as a result of major re-work for version 2.0.0. Please comment back if this is still an issue.

**Closed as completed by anickle060193** 2019-03-24 06:34 UTC
Labels: bug, Generic HTML
