### ISSUE TITLE
Spotify Reversion broke stuff.

### ISSUE THREAD

**Issue by kellub** [anickle060193/easy_control#109] opened 2017-03-15 16:52 UTC
Play/Pause controls (as well as others, probably) no longer work.
Opening a spotify link closes the active tab  and switches to the new tab. This means it stops playing what you were listening to and starts playing the content from the opened link.

**Comment by kellub** [comment] 2017-03-15 16:52
Also, I think autopause doesn't work anymore.

**Comment by anickle060193** [comment] 2017-03-17 00:41
Closing as duplicate of #108.

**Closed as completed by anickle060193** 2017-03-17 00:41 UTC
Labels: bug, Spotify
